config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model

    pg_search_scope :search_full_text, against: {
        description: 'A',
        user_name: 'B',
        url_image: 'C',
    },


    using: {
        tsearch: {
            prefix: true,
            any_word: true,
            dictionary: "spanish",
        }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend

    require 'pagy/extras/bootstrap'
end

#para agregar bootstrap en la paginación

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index 
    @pagy, @tweets = pagy(Tweet.all) #se agrega variable pagy
    if params[:query_text].present? #se agrega linea 7 para que el buscador sea funcional
      @pagy, @tweets = pagy(Tweet.search_full_text(params[:query_text])) 
    end #se agrega linea 8 tb para q reciba los parametros de query_text 
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @pagy, @tweets = pagy(Tweet.all) #se agrega variable pagy
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :user_name, :url_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end


#esto es para poder usar pagy_nav  en las vistas 

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>Twitter Leslie </title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <!-- recordar q acá se invocan los estilos-->
  <%= javascript_importmap_tags %>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="icon" type="image/png" href="<%= asset_path('logo.png') %>">
  <link href="estilos de letra de font de google" rel="stylesheet">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 bg-light">
        <nav class="navbar navbar-light text-left columizquierda">
          <ul class="nav flex-column">
            <li class="nav-item mt-5">
              <i class="icontwitter fa-brands fa-twitter"></i> 
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-solid fa-house"></i> <span class="label">
                <%= link_to "Inicio", tweets_path, class:"textotwitter1" %> </span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-solid fa-magnifying-glass"></i> <span class="label">Explorar</span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-regular fa-bell"></i> <span class="label">Notificaciones</span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-sharp fa-regular fa-envelope"></i><span class="label">Mensajes</span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-regular fa-rectangle-list"></i> <span class="label">Listas</span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-regular fa-bookmark"></i> <span class="label">Guardados</span>
            </li>
            <li class="nav-item mt-5">
              <i class="icon fa-regular fa-user"></i> <span class="label">Perfil</span>
            </li>
            <li class="nav-item mt-5 ">
              <button class="btn btn-info btn-lg" type="submit">
                <%= link_to "Twittear", new_tweet_path, class:"textotwitter2" %> </button>
            </li>
          </ul>
        </nav>
      </div>

      <div class="container col-md-6 yield">
        <%= yield %>
      </div>
      <div class="col-md-3 bg-light columnaderecha">
        <nav>
          <br> <br>
          <h1>Buscar</h1>
          <%= form_with url: tweets_path, method: :get do |form| %>
          <%= form.text_field :query_text, value: params[:query_text] %>
          <%= form.submit "Buscar", class: "btn btn-info" %>
          <% end %> <br>

          <h2> <b> Obtener verificación </b> </h2>
          <p> <b> Suscríbete para desbloquear nuevas <br> funciones </b> </p>
          <button class="btn btn-dark" type="submit"> <b> Obtener verificación </b> </button> <br> <br>

          <h2> Tendencias para ti </h2> <br>
          <div class="card" style="width: 18rem;">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <p> Entretenimiento Tendencia <br> <b> Germán </b> <br> 176 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> Reality </b> <br> 168 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> #Los80 </b> <br> 86 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> Japón </b> <br> 78 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> #Nintendo </b> <br> 76 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> #ZeldaTOTK </b> <br> 55 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> Gatos </b> <br> 45 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> #Tanhelaoquetaijuan </b> <br> 31 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> #Papasfritas </b> <br> 28 mil Tweets <p>
              </li>
              <li class="list-group-item">
                <p> Tendencias en Chile <br> <b> Vacaciones </b> <br> 25 mil Tweets <p>
              </li>
            </ul>
          </div>
        </nav>
        <footer>
          <p class="textofooter"> <a href="#">Condiciones de Servicio </a> <a href="#"> Política de privacidad </a> <br>
            <a href="#">Política de cookies </a> <a href="#"> Accesibilidad </a> <br> <a href="#"> Información de
              anuncios</a> <a href="#"> Más Opciones...</a> </p>
        </footer>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"> </script>
</body>

</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_name, "Nombre de usuario", style: "display: block" %> <br> 
    <%= form.text_field :user_name %> <br> <br>
  </div>

  <div>
    <%= form.label :description, "Cuentanos lo que estás pensando", style: "display: block" %>  <br> 
    <%= form.text_area :description, rows: 5, cols: 70 %> <br> <br>
  </div>
  
  <div>
    <%= form.label :url_image, "Pega la url de la imagen que quieras", style: "display: block" %>  <br> 
    <%= form.text_field :url_image %> <br> <br>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong> <%= tweet.user_name %> </strong>
    <%= "@#{tweet.user_name}" %>
  </p>

  <p>
    <strong>  </strong>
    <%= tweet.description %>
  </p>

  <p>
    <strong>  </strong>
    <img src="<%= tweet.url_image %>" alt="Imagenurl" width=500px heigh="400px">
  </p>

</div>


<!--código original 
   <p>
    <strong>Url image:</strong>
    <%= tweet.url_image %>
  </p>
-->

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Mostrar este tweet", @tweet %> |
  <%= link_to "Vuelve a todos los tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1> Inicio </h1>

<div class="inicio row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Para ti</h5>
        <p class="card-text"> ¡Porque tú nos importas! Revisa estas sugerencias especiales para ti</p>
        <a href="#" class="btn btn-primary">Revisar </a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Siguiendo</h5>
        <p class="card-text"> Mira las tendencias de tus seguidores.</p><br>
        <a href="#" class="btn btn-primary">Seguidores</a>
      </div>
    </div>
  </div>
</div>
<br> <br>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %> <!-- no olvidar para mostrar la paginación-->
</div>

<!-- 
<h1>Tweets</h1> 
--agregando ahora este formulario que es un buscador luego modif el controlador para q esto funcione ESTO LO PUSE EN EL LAYOUTS--
<%= form_with url: tweets_path, method: :get do |form| %>
    <%= form.text_field :query_text, value: params[:query_text] %>
    <%= form.submit "Buscar", class: "btn btn-primary" %>
<% end %>  <br>  <br> 
-->

<div id="tweets">
<!--modificando con if else end por si no existen coincidencias -->
  <% if @tweets.count > 0 %> <!-- linea agregada al final x si no existen coincidencias-->
    <% @tweets.order(id: :desc).each do |tweet| %> <!--acá le agregué lo del older id desc para que el ultimo tweet se vea de los 1ros-->
      <%= render tweet %>
      <p>
        <button class="btn btn-info btn-lg" type="submit">
        <%= link_to "Ver más...", tweet, class:"textotwitter2" %> </button>
      </p>
    <% end %>
    


  <% else %> <!-- en caso contrario -->
      <h1> No existen coincidencias </h1>
  <% end %>

</div>

app/views/tweets/new.html.erb
<div class="twittear">
<h1>Nuevo tweet</h1>

<%= render "form", tweet: @tweet %>
</div>

<br>

<div>
  <%= link_to "Volver a la vista principal", tweets_path %> <br> <br>
   <div class="d-flex justify-content-center">
     <%== pagy_bootstrap_nav(@pagy) %> <!-- no olvidar para mostrar la paginación-->
  </div>
</div>


<h1>Tweets</h1>

<div id="tweets">
    <% @tweets.order(id: :desc).each do |tweet| %>
      <%= render tweet %>
      <p>
       <button class="btn btn-info btn-lg" type="submit">
        <%= link_to "Ver más...", tweet, class:"textotwitter2" %> </button>
      </p>
    <% end %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Editar este tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Vuelve a todos los tweets", tweets_path %>

  <%= button_to "Eliminar este tweets", @tweet, method: :delete %>
</div>